export const recipes = [
  {
    name: "Spaghetti Carbonara",
    ingredients: [
      "spaghetti",
      "bacon",
      "eggs",
      "parmesan cheese",
      "black pepper",
      "salt",
    ],
    attributes: ["high-protein", "comfort food"],
  },
  {
    name: "Chicken Curry",
    ingredients: [
      "chicken breast",
      "onions",
      "garlic",
      "ginger",
      "tomatoes",
      "coconut milk",
      "curry powder",
      "salt",
      "vegetable oil",
      "cilantro",
    ],
    attributes: ["dairy-free", "gluten-free"],
  },
  {
    name: "Chocolate Chip Cookies",
    ingredients: [
      "all-purpose flour",
      "baking soda",
      "salt",
      "unsalted butter",
      "granulated sugar",
      "brown sugar",
      "vanilla extract",
      "eggs",
      "chocolate chips",
    ],
    attributes: ["vegetarian", "dessert"],
  },
  {
    name: "Quinoa Salad",
    ingredients: [
      "quinoa",
      "cucumber",
      "cherry tomatoes",
      "red onion",
      "feta cheese",
      "olive oil",
      "lemon juice",
      "salt",
      "pepper",
    ],
    attributes: ["vegetarian", "gluten-free", "low-carb"],
  },
  {
    name: "Vegan Tacos",
    ingredients: [
      "corn tortillas",
      "black beans",
      "avocado",
      "red cabbage",
      "cilantro",
      "lime",
      "salsa",
      "salt",
      "pepper",
    ],
    attributes: ["vegan", "gluten-free", "dairy-free"],
  },
  {
    name: "Avocado Toast",
    ingredients: [
      "bread",
      "avocado",
      "lemon juice",
      "salt",
      "pepper",
      "red chili flakes",
    ],
    attributes: ["vegetarian", "vegan option", "quick"],
  },
  {
    name: "Beef Stroganoff",
    ingredients: [
      "beef",
      "onions",
      "mushrooms",
      "sour cream",
      "beef broth",
      "flour",
      "butter",
      "egg noodles",
      "salt",
      "pepper",
    ],
    attributes: ["comfort food", "high-protein"],
  },
  {
    name: "Mango Smoothie",
    ingredients: ["mango", "banana", "yogurt", "orange juice", "honey"],
    attributes: ["vegetarian", "gluten-free", "quick"],
  },
  {
    name: "Grilled Cheese Sandwich",
    ingredients: ["bread", "cheddar cheese", "butter"],
    attributes: ["vegetarian", "quick", "comfort food"],
  },
  {
    name: "Caesar Salad",
    ingredients: [
      "romaine lettuce",
      "croutons",
      "parmesan cheese",
      "caesar dressing",
      "chicken breast",
      "lemon juice",
      "salt",
      "pepper",
    ],
    attributes: ["gluten-free option", "high-protein"],
  },
  {
    name: "Lentil Soup",
    ingredients: [
      "lentils",
      "carrots",
      "celery",
      "onions",
      "garlic",
      "tomatoes",
      "vegetable broth",
      "olive oil",
      "salt",
      "pepper",
    ],
    attributes: ["vegan", "gluten-free", "high-fiber"],
  },
  {
    name: "Caprese Salad",
    ingredients: [
      "tomatoes",
      "mozzarella cheese",
      "basil",
      "olive oil",
      "balsamic vinegar",
      "salt",
      "pepper",
    ],
    attributes: ["vegetarian", "gluten-free", "low-carb"],
  },
  {
    name: "Shrimp Scampi",
    ingredients: [
      "shrimp",
      "garlic",
      "butter",
      "lemon juice",
      "white wine",
      "parsley",
      "salt",
      "pepper",
      "angel hair pasta",
    ],
    attributes: ["seafood", "quick"],
  },
  {
    name: "Stuffed Bell Peppers",
    ingredients: [
      "bell peppers",
      "ground beef",
      "rice",
      "onions",
      "tomatoes",
      "cheddar cheese",
      "garlic",
      "olive oil",
      "salt",
      "pepper",
    ],
    attributes: ["gluten-free", "high-protein"],
  },
  {
    name: "Banana Pancakes",
    ingredients: [
      "bananas",
      "eggs",
      "baking powder",
      "vanilla extract",
      "cinnamon",
      "butter",
      "maple syrup",
    ],
    attributes: ["vegetarian", "gluten-free option", "breakfast"],
  },
  {
    name: "Chickpea Salad",
    ingredients: [
      "chickpeas",
      "cucumber",
      "cherry tomatoes",
      "red onion",
      "feta cheese",
      "olive oil",
      "lemon juice",
      "parsley",
      "salt",
      "pepper",
    ],
    attributes: ["vegetarian", "gluten-free", "high-fiber"],
  },
  {
    name: "Eggplant Parmesan",
    ingredients: [
      "eggplant",
      "mozzarella cheese",
      "parmesan cheese",
      "tomato sauce",
      "bread crumbs",
      "eggs",
      "olive oil",
      "salt",
      "pepper",
    ],
    attributes: ["vegetarian", "comfort food"],
  },
  {
    name: "Fish Tacos",
    ingredients: [
      "fish fillets",
      "corn tortillas",
      "cabbage",
      "lime",
      "cilantro",
      "sour cream",
      "avocado",
      "salt",
      "pepper",
    ],
    attributes: ["seafood", "gluten-free"],
  },
  {
    name: "Greek Yogurt Parfait",
    ingredients: [
      "greek yogurt",
      "honey",
      "granola",
      "berries",
      "nuts",
      "vanilla extract",
    ],
    attributes: ["vegetarian", "gluten-free option", "breakfast"],
  },
  {
    name: "Vegetable Stir Fry",
    ingredients: [
      "broccoli",
      "bell peppers",
      "carrots",
      "snap peas",
      "soy sauce",
      "ginger",
      "garlic",
      "olive oil",
      "rice",
      "salt",
      "pepper",
    ],
    attributes: ["vegan", "gluten-free", "quick"],
  },
  {
    name: "Pasta Primavera",
    ingredients: [
      "pasta",
      "zucchini",
      "yellow squash",
      "bell peppers",
      "cherry tomatoes",
      "garlic",
      "olive oil",
      "parmesan cheese",
      "basil",
      "salt",
      "pepper",
    ],
    attributes: ["vegetarian", "quick"],
  },
  {
    name: "Chicken Salad",
    ingredients: [
      "chicken breast",
      "celery",
      "red grapes",
      "mayonnaise",
      "lemon juice",
      "salt",
      "pepper",
    ],
    attributes: ["gluten-free", "high-protein"],
  },
  {
    name: "Peanut Butter Cookies",
    ingredients: [
      "peanut butter",
      "sugar",
      "eggs",
      "vanilla extract",
      "baking soda",
      "salt",
    ],
    attributes: ["vegetarian", "gluten-free", "dessert"],
  },
  {
    name: "Ratatouille",
    ingredients: [
      "eggplant",
      "zucchini",
      "yellow squash",
      "bell peppers",
      "tomatoes",
      "onions",
      "garlic",
      "olive oil",
      "herbs de provence",
      "salt",
      "pepper",
    ],
    attributes: ["vegetarian", "vegan", "gluten-free"],
  },
  {
    name: "Pulled Pork Sandwich",
    ingredients: [
      "pork shoulder",
      "bbq sauce",
      "hamburger buns",
      "coleslaw",
      "pickles",
    ],
    attributes: ["comfort food", "high-protein"],
  },
  {
    name: "Tofu Stir Fry",
    ingredients: [
      "tofu",
      "broccoli",
      "bell peppers",
      "carrots",
      "snap peas",
      "soy sauce",
      "ginger",
      "garlic",
      "olive oil",
      "rice",
      "salt",
      "pepper",
    ],
    attributes: ["vegan", "gluten-free", "high-protein"],
  },
  {
    name: "French Toast",
    ingredients: [
      "bread",
      "eggs",
      "milk",
      "vanilla extract",
      "cinnamon",
      "butter",
      "maple syrup",
    ],
    attributes: ["vegetarian", "comfort food", "breakfast"],
  },
  {
    name: "Chicken Noodle Soup",
    ingredients: [
      "chicken breast",
      "carrots",
      "celery",
      "onions",
      "garlic",
      "chicken broth",
      "egg noodles",
      "olive oil",
      "salt",
      "pepper",
    ],
    attributes: ["comfort food", "high-protein"],
  },
  {
    name: "Pasta Salad",
    ingredients: [
      "pasta",
      "cherry tomatoes",
      "cucumber",
      "red onion",
      "feta cheese",
      "olive oil",
      "lemon juice",
      "oregano",
      "salt",
      "pepper",
    ],
    attributes: ["vegetarian", "quick", "low-carb"],
  },
  {
    name: "Spinach and Feta Stuffed Chicken",
    ingredients: [
      "chicken breast",
      "spinach",
      "feta cheese",
      "garlic",
      "olive oil",
      "salt",
      "pepper",
    ],
    attributes: ["gluten-free", "high-protein"],
  },
  {
    name: "Mushroom Risotto",
    ingredients: [
      "arborio rice",
      "mushrooms",
      "onions",
      "garlic",
      "white wine",
      "parmesan cheese",
      "butter",
      "vegetable broth",
      "salt",
      "pepper",
    ],
    attributes: ["vegetarian", "comfort food"],
  },
  {
    name: "Cauliflower Rice",
    ingredients: ["cauliflower", "olive oil", "garlic", "salt", "pepper"],
    attributes: ["vegetarian", "vegan", "gluten-free", "low-carb"],
  },
  {
    name: "Baked Salmon",
    ingredients: [
      "salmon fillets",
      "lemon",
      "dill",
      "olive oil",
      "salt",
      "pepper",
    ],
    attributes: ["seafood", "gluten-free", "high-protein"],
  },
  {
    name: "Pesto Pasta",
    ingredients: [
      "pasta",
      "basil",
      "pine nuts",
      "parmesan cheese",
      "garlic",
      "olive oil",
      "salt",
      "pepper",
    ],
    attributes: ["vegetarian", "quick"],
  },
  {
    name: "Beef Tacos",
    ingredients: [
      "ground beef",
      "taco seasoning",
      "corn tortillas",
      "cheddar cheese",
      "lettuce",
      "tomatoes",
      "sour cream",
      "salsa",
      "avocado",
      "salt",
      "pepper",
    ],
    attributes: ["comfort food", "high-protein"],
  },
  {
    name: "Margarita Pizza",
    ingredients: [
      "tomato sauce",
      "mozzarella cheese",
      "fresh basil",
      "olive oil",
      "pizza dough",
      "salt",
      "pepper",
    ],
    attributes: ["vegetarian", "quick", "comfort food"],
  },
  {
    name: "Chicken Alfredo",
    ingredients: [
      "fettuccine",
      "chicken breast",
      "heavy cream",
      "parmesan cheese",
      "butter",
      "garlic",
      "salt",
      "pepper",
    ],
    attributes: ["comfort food", "high-protein"],
  },
  {
    name: "Apple Pie",
    ingredients: [
      "apples",
      "sugar",
      "cinnamon",
      "nutmeg",
      "butter",
      "flour",
      "pie crust",
    ],
    attributes: ["vegetarian", "dessert"],
  },
  {
    name: "Tuna Salad",
    ingredients: [
      "canned tuna",
      "celery",
      "red onion",
      "mayonnaise",
      "lemon juice",
      "salt",
      "pepper",
    ],
    attributes: ["gluten-free", "high-protein"],
  },
  {
    name: "Rice and Beans",
    ingredients: [
      "rice",
      "black beans",
      "onions",
      "garlic",
      "bell peppers",
      "cumin",
      "chili powder",
      "salt",
      "pepper",
    ],
    attributes: ["vegetarian", "vegan", "gluten-free", "high-protein"],
  },
  {
    name: "Butternut Squash Soup",
    ingredients: [
      "butternut squash",
      "onions",
      "garlic",
      "vegetable broth",
      "coconut milk",
      "curry powder",
      "cinnamon",
      "salt",
      "pepper",
    ],
    attributes: ["vegetarian", "vegan", "gluten-free"],
  },
  {
    name: "Lemon Chicken",
    ingredients: [
      "chicken breast",
      "lemon",
      "garlic",
      "butter",
      "olive oil",
      "salt",
      "pepper",
    ],
    attributes: ["gluten-free", "high-protein"],
  },
  {
    name: "Cheeseburger",
    ingredients: [
      "ground beef",
      "cheddar cheese",
      "hamburger buns",
      "lettuce",
      "tomato",
      "onion",
      "pickles",
      "ketchup",
      "mustard",
      "salt",
      "pepper",
    ],
    attributes: ["comfort food", "high-protein"],
  },
  {
    name: "Pumpkin Bread",
    ingredients: [
      "flour",
      "sugar",
      "pumpkin",
      "eggs",
      "butter",
      "cinnamon",
      "nutmeg",
      "baking soda",
      "salt",
    ],
    attributes: ["vegetarian", "dessert"],
  },
  {
    name: "Shakshuka",
    ingredients: [
      "eggs",
      "tomatoes",
      "red bell pepper",
      "onions",
      "garlic",
      "cumin",
      "paprika",
      "cayenne pepper",
      "olive oil",
      "salt",
      "pepper",
    ],
    attributes: ["vegetarian", "gluten-free", "high-protein"],
  },
  {
    name: "Cobb Salad",
    ingredients: [
      "romaine lettuce",
      "chicken breast",
      "bacon",
      "avocado",
      "tomatoes",
      "hard-boiled eggs",
      "blue cheese",
      "red wine vinaigrette",
      "salt",
      "pepper",
    ],
    attributes: ["gluten-free", "high-protein"],
  },
  {
    name: "Pulled Chicken",
    ingredients: [
      "chicken breast",
      "bbq sauce",
      "hamburger buns",
      "coleslaw",
      "pickles",
    ],
    attributes: ["comfort food", "high-protein"],
  },
  {
    name: "Lemon Bars",
    ingredients: [
      "flour",
      "sugar",
      "butter",
      "eggs",
      "lemon juice",
      "lemon zest",
      "powdered sugar",
    ],
    attributes: ["vegetarian", "dessert"],
  },
  {
    name: "Chicken Enchiladas",
    ingredients: [
      "chicken breast",
      "tortillas",
      "enchilada sauce",
      "cheddar cheese",
      "onions",
      "garlic",
      "sour cream",
      "cilantro",
      "salt",
      "pepper",
    ],
    attributes: ["comfort food", "high-protein"],
  },
  {
    name: "Tiramisu",
    ingredients: [
      "ladyfingers",
      "espresso",
      "mascarpone cheese",
      "eggs",
      "sugar",
      "cocoa powder",
    ],
    attributes: ["vegetarian", "dessert"],
  },
  {
    name: "Chicken Parmesan",
    ingredients: [
      "chicken breast",
      "flour",
      "eggs",
      "breadcrumbs",
      "marinara sauce",
      "mozzarella cheese",
      "parmesan cheese",
      "olive oil",
      "salt",
      "pepper",
    ],
    attributes: ["comfort food", "high-protein"],
  },
  {
    name: "Ravioli",
    ingredients: ["ravioli", "marinara sauce", "parmesan cheese", "basil"],
    attributes: ["vegetarian", "comfort food"],
  },
  {
    name: "Pancakes",
    ingredients: [
      "flour",
      "sugar",
      "baking powder",
      "milk",
      "eggs",
      "butter",
      "maple syrup",
    ],
    attributes: ["vegetarian", "comfort food", "breakfast"],
  },
  {
    name: "Pad Thai",
    ingredients: [
      "rice noodles",
      "shrimp",
      "tofu",
      "bean sprouts",
      "eggs",
      "peanuts",
      "lime",
      "fish sauce",
      "soy sauce",
      "sugar",
      "garlic",
      "vegetable oil",
    ],
    attributes: ["seafood", "gluten-free"],
  },
  {
    name: "Chicken Fajitas",
    ingredients: [
      "chicken breast",
      "bell peppers",
      "onions",
      "fajita seasoning",
      "tortillas",
      "sour cream",
      "salsa",
      "guacamole",
      "salt",
      "pepper",
    ],
    attributes: ["comfort food", "high-protein"],
  },
  {
    name: "Key Lime Pie",
    ingredients: [
      "graham cracker crust",
      "sweetened condensed milk",
      "key lime juice",
      "eggs",
      "sugar",
      "whipped cream",
    ],
    attributes: ["vegetarian", "dessert"],
  },
  {
    name: "Chicken Tenders",
    ingredients: [
      "chicken breast",
      "flour",
      "eggs",
      "breadcrumbs",
      "seasoning",
      "honey mustard sauce",
      "french fries",
    ],
    attributes: ["comfort food", "high-protein"],
  },
  {
    name: "Mushroom Soup",
    ingredients: [
      "mushrooms",
      "onions",
      "garlic",
      "vegetable broth",
      "cream",
      "thyme",
      "butter",
      "salt",
      "pepper",
    ],
    attributes: ["vegetarian", "comfort food"],
  },
  {
    name: "Cinnamon Rolls",
    ingredients: [
      "flour",
      "sugar",
      "butter",
      "milk",
      "eggs",
      "cinnamon",
      "yeast",
      "cream cheese",
      "powdered sugar",
    ],
    attributes: ["vegetarian", "dessert"],
  },
  {
    name: "Chicken Pot Pie",
    ingredients: [
      "chicken breast",
      "carrots",
      "peas",
      "onions",
      "garlic",
      "potatoes",
      "chicken broth",
      "flour",
      "butter",
      "pie crust",
    ],
    attributes: ["comfort food", "high-protein"],
  },
  {
    name: "Tomato Basil Soup",
    ingredients: [
      "tomatoes",
      "basil",
      "onions",
      "garlic",
      "vegetable broth",
      "olive oil",
      "salt",
      "pepper",
      "cream",
    ],
    attributes: ["vegetarian", "gluten-free", "comfort food"],
  },
  {
    name: "Spinach and Feta Stuffed Chicken",
    ingredients: [
      "chicken breast",
      "spinach",
      "feta cheese",
      "garlic",
      "olive oil",
      "salt",
      "pepper",
    ],
    attributes: ["gluten-free", "high-protein", "low-carb"],
  },
  {
    name: "Sweet Potato Fries",
    ingredients: ["sweet potatoes", "olive oil", "salt", "pepper", "paprika"],
    attributes: ["vegan", "gluten-free", "snack"],
  },
  {
    name: "Egg Fried Rice",
    ingredients: [
      "rice",
      "eggs",
      "peas",
      "carrots",
      "soy sauce",
      "green onions",
      "garlic",
      "ginger",
      "vegetable oil",
      "salt",
      "pepper",
    ],
    attributes: ["vegetarian", "quick", "comfort food"],
  },
  {
    name: "Blueberry Muffins",
    ingredients: [
      "all-purpose flour",
      "sugar",
      "baking powder",
      "salt",
      "butter",
      "eggs",
      "milk",
      "blueberries",
      "vanilla extract",
    ],
    attributes: ["vegetarian", "dessert", "breakfast"],
  },
  {
    name: "Quiche Lorraine",
    ingredients: [
      "pie crust",
      "bacon",
      "eggs",
      "heavy cream",
      "gruyere cheese",
      "onions",
      "salt",
      "pepper",
    ],
    attributes: ["comfort food", "brunch"],
  },
  {
    name: "Tuna Salad",
    ingredients: [
      "tuna",
      "mayonnaise",
      "celery",
      "red onion",
      "lemon juice",
      "salt",
      "pepper",
    ],
    attributes: ["gluten-free", "quick", "high-protein"],
  },
  {
    name: "Cucumber Sandwiches",
    ingredients: [
      "bread",
      "cucumber",
      "cream cheese",
      "dill",
      "salt",
      "pepper",
    ],
    attributes: ["vegetarian", "snack", "quick"],
  },
  {
    name: "Beef Tacos",
    ingredients: [
      "ground beef",
      "taco seasoning",
      "corn tortillas",
      "lettuce",
      "tomatoes",
      "cheddar cheese",
      "sour cream",
      "salsa",
    ],
    attributes: ["gluten-free option", "quick", "comfort food"],
  },
  {
    name: "Pumpkin Pie",
    ingredients: [
      "pie crust",
      "pumpkin puree",
      "eggs",
      "sugar",
      "cinnamon",
      "nutmeg",
      "ginger",
      "cloves",
      "evaporated milk",
    ],
    attributes: ["dessert", "vegetarian", "holiday"],
  },
  {
    name: "Chicken Marsala",
    ingredients: [
      "chicken breast",
      "flour",
      "butter",
      "olive oil",
      "mushrooms",
      "marsala wine",
      "chicken broth",
      "garlic",
      "salt",
      "pepper",
    ],
    attributes: ["comfort food", "high-protein"],
  },
  {
    name: "Broccoli Cheddar Soup",
    ingredients: [
      "broccoli",
      "cheddar cheese",
      "onions",
      "garlic",
      "vegetable broth",
      "milk",
      "flour",
      "butter",
      "salt",
      "pepper",
    ],
    attributes: ["vegetarian", "comfort food"],
  },
  {
    name: "Carnitas",
    ingredients: [
      "pork shoulder",
      "orange juice",
      "lime juice",
      "garlic",
      "cumin",
      "oregano",
      "salt",
      "pepper",
      "tortillas",
      "salsa",
      "guacamole",
    ],
    attributes: ["comfort food", "high-protein"],
  },
  {
    name: "Lemon Garlic Shrimp",
    ingredients: [
      "shrimp",
      "butter",
      "olive oil",
      "garlic",
      "lemon juice",
      "parsley",
      "salt",
      "pepper",
    ],
    attributes: ["seafood", "gluten-free", "high-protein"],
  },
  {
    name: "Chicken Piccata",
    ingredients: [
      "chicken breast",
      "flour",
      "butter",
      "olive oil",
      "lemon juice",
      "capers",
      "chicken broth",
      "garlic",
      "salt",
      "pepper",
    ],
    attributes: ["comfort food", "high-protein"],
  },
  {
    name: "Ricotta Stuffed Shells",
    ingredients: [
      "jumbo pasta shells",
      "ricotta cheese",
      "parmesan cheese",
      "mozzarella cheese",
      "eggs",
      "parsley",
      "marinara sauce",
      "salt",
      "pepper",
    ],
    attributes: ["vegetarian", "comfort food"],
  },
];
